### ISSUE TITLE
ClassNotFoundException: is.hail.io.bgen.LoadBgenPartition

### ISSUE THREAD

**Issue by Angelogeb** [hms-dbmi/hail-on-AWS-spot-instances#4] opened 2019-04-24 10:37 UTC
Hi,

I was trying to run the following snippet on the cluster setup with this repo

```python
ds = hl.import_bgen(
    BGEN_FILE,
    entry_fields=ENTRY_FIELDS,
    sample_file=SAMPLE_FILE
)

ds.write(MATRIX_PATH)
```

but I'm getting `ClassNotFoundException: is.hail.io.bgen.LoadBgenPartition` (Hail version: 0.2.13-b1007cadf2bb).

It is not possible to perform any operation on BGENs.

Any solution?

**Comment by Angelogeb** [comment] 2019-04-28 09:01
Apparently `hail-all-spark.jar` and `hail-python.zip` weren't copied on the worker nodes. The following error was written in the master node `/tmp/cloudcreation_log.out`:
```
Warning: Permanently added '172.***.***.***' (ECDSA) to the list of known hosts.
Permission denied (publickey).
lost connection
Permission denied (publickey).
lost connection
Warning: Permanently added '172.***.***.***' (ECDSA) to the list of known hosts.
Permission denied (publickey).
lost connection
Permission denied (publickey).
lost connection
Keys successfully copied to the worker nodes
```

**Comment by biocdeniz** [comment] 2019-06-11 14:50
Hi @Angelogeb, 

Was this solved? I noticed that the `hail-all-spark.jar` and `hail-python.zip` files sometimes are missing (Hail did not compile) but I haven't found out why as the compilation simply fails. This error coincidentally started to occur after the Hail upgrade to Spark 2.4, we use Spark 2.3.0, but again I really haven't found a pattern as it doesn't happen all the time. However, this is a very easy fix. In case the `.jar and .zip` files are missing, login to the master node, `cd` into `/opt/hail-on-AWS-spot-instances/src/` and execute `sh hail_build.sh` to re-compile Hail. This operation takes 3-4 minutes and then both the `.jar and .zip` files should be available at the `HOME` directory.  

You can always go to the log (`/tmp/cloudcreation_log.out`) and check for output and errors.

I hope this helps.

**Comment by Angelogeb** [comment] 2019-06-16 09:05
Hi,

Yes. In my case it wasn't the build that was failing but the `scp` of the jars to worker nodes.
I'm currently having another issue: the same code (and data) that was running in previous versions of hail/spark is running out of memory with the current setup (cluster launched through this repo and hail cloned from master).

Any idea on what's going on and do you plan to upgrade the scripts for newer versions?

**Comment by biocdeniz** [comment] 2019-06-19 14:42
Hi @Angelogeb,

If you are able to successfully spin your cluster (with Hail installed) but the memory issue you are facing occurs after executing a Hail command, then the issue is on the cluster setup. To fix this you should either increase the size of your cluster (more workers) or the instance type for your worker nodes (or even your master node). The instance types listed in the config file of this repo are just suggested and you can always change them to your convenience. 

You may be executing a task that becomes memory intensive (like saving a big annotated `.mt` file) and therefore your task is running out of memory. There are many ways for you to monitor the [health of your cluster](<https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-troubleshoot-slow-4.html>) to help you realize where the error comes from. Also, you can ask these kind of questions directly on the [Hail chat](<https://hail.zulipchat.com/login/>), they are very responsive. 

I'm closing this issue.

**Closed as completed by biocdeniz** 2019-06-19 14:42 UTC
